server:
  port: -1 #web服务端口，由于我们不需要使用web服务，所以将其设为随机端口

dubbo:
  protocol:
    port: -1 #dubbo服务端口，我们无需知道dubbo服务运行在哪个端口，故也将其设为随机端口
  application:
    name: dubbo-provider #dubbo服务名称
  scan:
    base-packages: com.gx.server.service #dubbo服务所在包路径
  registry:
    address: zookeeper://112.126.59.191:2181 #注册中心地址

logging:
  level: info #设置服务的日志输出级别为debug级level.com.czh.dubbo.provider.service=debug
